#!/bin/sh
#
#
# This file is edited by vim
#

show_progress_bar() {
    USED=`expr \( $1 + 1 \) / 2`
    FREE=`expr 50 - $1 / 2`
    if [ ${USED} -ne 0 ]; then
        printf "\033[41m%${USED}s"
    fi
    if [ ${FREE} -ne 0 ]; then
        printf "\033[46m%${FREE}s"
    fi
    printf "\033[m"
}

show_disk_usage() {
    printf "\033[1;33m= Disk Usage ===========================================================\033[m\n"

	# root directory
	Q_FULL=`df -hBG / | tail -n +2 | awk '{ print $2 }' | awk -F "G" '{ print $1 }'`
	Q_USED=`df -hBG / | tail -n +2 | awk '{ print $3 }' | awk -F "G" '{ print $1 }'`

	if [ -n "${Q_FULL:=0}" -a ${Q_FULL} -gt 0 ]; then
		PERCENT=`expr ${Q_USED} \* 100 / ${Q_FULL}`
		printf " \033[1mRoot:\033[m "
		show_progress_bar ${PERCENT}
		printf " ${PERCENT}%% ${Q_USED}/${Q_FULL} GB\n"
		echo
	fi

	# home directory
	Q_FULL=`df -hBG /home | tail -n +2 | awk '{ print $2 }' | awk -F "G" '{ print $1 }'`
	Q_USED=`df -hBG /home | tail -n +2 | awk '{ print $3 }' | awk -F "G" '{ print $1 }'`

	if [ -n "${Q_FULL:=0}" -a ${Q_FULL} -gt 0 ]; then
		PERCENT=`expr ${Q_USED} \* 100 / ${Q_FULL}`
		printf " \033[1mHome:\033[m "
		show_progress_bar ${PERCENT}
		printf " ${PERCENT}%% ${Q_USED}/${Q_FULL} GB\n"
		echo
	fi
}

showInfoAndExecShell() {
	/usr/lib/lab-script/mkmotd

	show_disk_usage

	# User's process Status
	printf "\033[40;33m= Process ==============================================================\033[0m\n"
	ps

	# Workstation Status
	printf "\033[40;33m= Information ==========================================================\033[0m\n"
	printf "\033[40;32mCurrent Time:\033[0m "
	date
	printf "\033[40;32mOnline Users:\033[0m "
	who -q | tail -1 | awk -F'=' '{print $2}'
	if [ -f "/run/systemd/shutdown/scheduled" ]; then
		printf "\033[40;32mNext shutdown time:\033[0m "
		USEC=`awk -F "=" 'NR==1{ print $2}' /run/systemd/shutdown/scheduled`
		SEC=`expr $USEC / 1000000`
		date -d @$SEC +"%Y/%m/%d %H:%M:%S"
	fi

	# Lab Announce
	printf "\033[40;33m= Lab Announce =========================================================\033[0m\n"
	printf "\033[40;96mhttps://sites.google.com/nctu.edu.tw/adclab-nctu/home\033[0m "
	
	echo 
	echo

	# check if user's SHELL has been installed
	if [ ! -f ${SHELL} ]; then
		echo "Sorry, your login shell ($(SHELL)) has not been installed on this machine"
		echo "Use /bin/sh as your default shell :)"
	fi

	# Login shell uses "-l", except sh
	if [ "${SHELL}" != "/bin/sh" ]; then
		exec ${SHELL} -l
	else
		source /etc/profile
		exec ${SHELL}
	fi
}

###
# main() flow
###

# For remote command execution
if [ -n "${SSH_ORIGINAL_COMMAND}" ]; then
	exec ${SHELL} -c "${SSH_ORIGINAL_COMMAND}"
fi

# Excute shell
if [ $# -eq 0 ]; then   # interactive shell
	showInfoAndExecShell
else					# non-interactive shell
	exec ${SHELL} $1 "$2"
fi
